language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - gcc-8
#    - libgtest-dev
    - cmake
    - libblas-dev
    - liblapack-dev

before_script:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
# dlib
- wget http://dlib.net/files/dlib-19.16.tar.bz2
- tar xf dlib-19.16.tar.bz2
- cd dlib-19.16
- mkdir build
- cd build
- cmake ..
- cmake --build . --config Release
- sudo make install
- sudo ldconfig
- cd "${TRAVIS_BUILD_DIR}"
# gtest
#- cd /usr/src/gtest
#- sudo cmake .
#- sudo make
#- sudo cp *.a /usr/lib
#- cd "${TRAVIS_BUILD_DIR}"

script:
- cmake .
- cmake --build .
#- ctest -VV # run GTest
#- cmake --build . --target test
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T realty-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -u artbataev:$BINTRAY_API_KEY "https://api.bintray.com/content/artbataev1/Otus_Assignments/Otus_Cpp_16/$TRAVIS_BUILD_NUMBER/realty-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;publish=1"
  on:
    branch: master
